aufgabe2/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('todo/', include('todo.urls')),
    path('admin/', admin.site.urls),
]

aufgabe2/todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'
urlpatterns = [
    # ex: /todo/
    path('', views.index, name='index'),
    # ex: /todo/5/edit
    path('<int:task_id>/edit', views.edit, name='edit'),
    # ex: /todo/5/saveedit
    path('<int:task_id>/saveedit', views.saveedit, name='saveedit'),
    # ex: /todo/5/delete
    path('<int:task_id>/delete', views.delete, name='delete'),
    # ex: /todo/new
    path('new', views.new, name='new'),
    # ex: /todo/savenew
    path('savenew', views.savenew, name='savenew'),
    # ex: /todo/disclaimer
    path('disclaimer', views.disclaimer, name='disclaimer')

]

aufgabe2/todo/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Task(models.Model):
    task_text = models.CharField(max_length=200)
    deadline = models.DateField('Deadline')
    progress = models.IntegerField(default=0)
    done = models.IntegerField(default=0)
    def __str__(self):
        return self.task_text

aufgabe2/todo/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Task

# Create your views here.

def index(request):
    task_list = Task.objects.order_by('deadline')
    return render(request, 'todo/index.html', {'task_list': task_list})

def saveedit(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    try:
        new_task = request.POST['todo']
        if not new_task:
            return render(request, 'todo/content/edittodo.html', {'task': task, 'error_message': "An Error occured."})
        new_deadline = request.POST['deadline']
        if not new_deadline:
            return render(request, 'todo/content/edittodo.html', {'task': task, 'error_message': "An Error occured."})
        new_progress = request.POST['progress']
        if int(new_progress)<0 or int(new_progress)>100:
            return render(request, 'todo/content/edittodo.html', {'task': task, 'error_message': "An Error occured."})
    except:
        return render(request, 'todo/content/edittodo.html', {
            'task': task,
            'error_message': "An Error occured.",
        })
    else:
        task.task_text = new_task
        task.deadline = new_deadline
        task.progress = new_progress
        task.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('todo:index'))

def savenew(request):
    try:
        new_task = request.POST['todo']
        if not new_task:
            return render(request, 'todo/content/newtodo.html', {'error_message': "An Error occured."})
        new_deadline = request.POST['deadline']
        if not new_deadline:
            return render(request, 'todo/content/newtodo.html', {'error_message': "An Error occured."})
        new_progress = request.POST['progress']
        if int(new_progress)<0 or int(new_progress)>100:
            return render(request, 'todo/content/newtodo.html', {'error_message': "An Error occured."})
    except:
        return render(request, 'todo/content/newtodo.html', {'error_message': "An Error occured."})
    else:
        new_todo = Task(task_text=new_task, deadline=new_deadline, progress=new_progress)
        new_todo.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('todo:index'))

def edit(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    return render(request, 'todo/content/edittodo.html', {'task': task})

def delete(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    task.delete()
    # Always return an HttpResponseRedirect after successfully dealings
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('todo:index'))

def new(request):
    return render(request, 'todo/content/newtodo.html', {})

def disclaimer(request):
    return render(request, 'todo/content/disclaimer.html', {})

aufgabe2/todo/templates/todo/content/disclaimer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" a href="{% static 'todo/css/bootstrap.css' %}" />
    <title>Disclaimer</title>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'todo:index' %}">ToDo List</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'todo:new' %}">New</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:disclaimer' %}">Disclaimer</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Disclaimer</h1>
            </div>
        </div>
        <div class="row">
            <div class="text-center col">
                <img src="{% static 'todo/images/arne.png' %}" width="200" class="rounded-circle" alt="Arne Seelisch" />
                <h3>Arne Seelisch</h3>
            </div>
            <div class="text-center col">
                <img src="{% static 'todo/images/furkan.png' %}" width="200" class="rounded-circle" alt="Furkan Tas" />
                <h3>Furkan Tas</h3>
            </div>
        </div>
    </div>

    <!-- How to use bootstrap -> https://www.youtube.com/watch?v=zcUUE0E_qAs -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'todo/js/jquery-3.4.0.slim.min.js' %}"></script>
    <script src="{% static 'todo/js/popper.min.js' %}"></script> <!-- https://github.com/FezVrasta/popper.js/blob/master/docs/_includes/tooltip-documentation.md -->
    <script src="{% static 'todo/js/bootstrap.js' %}"></script> <!-- https://getbootstrap.com/docs/4.3/getting-started/introduction/ -->
</body>
</html>

aufgabe2/todo/templates/todo/content/edittodo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" a href="{% static 'todo/css/bootstrap.css' %}" />
    <title>Edit Todo</title>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'todo:index' %}">ToDo List</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'todo:new' %}">New</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:disclaimer' %}">Disclaimer</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Edit Todo</h1>
            </div>
        </div>
        <div class="row">
            <div class="col">
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                <form action="{% url 'todo:saveedit' task.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-auto">
                            <input type="text" value="{{ task.task_text }}" class="form-control" placeholder="ToDo" name="todo" />
                        </div>
                        <div class="col-auto">
                            <input type="date" value="{{ task.deadline|date:"Y-m-d" }}" class="form-control" name="deadline" />
                        </div>
                        <div class="col-auto">
                            <!-- <input type="range" name="progress" class="form-control-range" min="0" max="100" step="1" value="0" /> -->
                            <input type="text" value="{{ task.progress }}" class="form-control" placeholder="progress" name="progress" />
                        </div>
                        <div class="col-auto">
                            <input type="submit" class="btn btn-primary mb-2 btn-own" value="save" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- How to use bootstrap -> https://www.youtube.com/watch?v=zcUUE0E_qAs -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'todo/js/jquery-3.4.0.slim.min.js' %}"></script>
    <script src="{% static 'todo/js/popper.min.js' %}"></script> <!-- https://github.com/FezVrasta/popper.js/blob/master/docs/_includes/tooltip-documentation.md -->
    <script src="{% static 'todo/js/bootstrap.js' %}"></script> <!-- https://getbootstrap.com/docs/4.3/getting-started/introduction/ -->
</body>
</html>

aufgabe2/todo/templates/todo/content/newtodo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" a href="{% static 'todo/css/bootstrap.css' %}" />
    <title>New Todo</title>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'todo:index' %}">ToDo List</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'todo:new' %}">New</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:disclaimer' %}">Disclaimer</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>New Todo</h1>
            </div>
        </div>
        <div class="row">
            <div class="col">
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                <form action="{% url 'todo:savenew' %}" method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-auto">
                            <input type="text" class="form-control" placeholder="ToDo" name="todo" />
                        </div>
                        <div class="col-auto">
                            <input type="date" class="form-control" name="deadline" />
                        </div>
                        <div class="col-auto">
                            <!-- <input type="range" name="progress" class="form-control-range" min="0" max="100" step="1" value="0" /> -->
                            <input type="text" class="form-control" placeholder="progress" name="progress" />
                        </div>
                        <div class="col-auto">
                            <input type="submit" class="btn btn-primary mb-2 btn-own" value="save" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- How to use bootstrap -> https://www.youtube.com/watch?v=zcUUE0E_qAs -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'todo/js/jquery-3.4.0.slim.min.js' %}"></script>
    <script src="{% static 'todo/js/popper.min.js' %}"></script> <!-- https://github.com/FezVrasta/popper.js/blob/master/docs/_includes/tooltip-documentation.md -->
    <script src="{% static 'todo/js/bootstrap.js' %}"></script> <!-- https://getbootstrap.com/docs/4.3/getting-started/introduction/ -->
</body>
</html>

aufgabe2/todo/templates/todo/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" a href="{% static 'todo/css/bootstrap.css' %}" />
    <title>ToDo List</title>
</head>
<body>
    <!-- <div w3-include-html="content/navbar.html"></div>https://getbootstrap.com/docs/4.0/components/navbar/ -->
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'todo:index' %}">ToDo List</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'todo:new' %}">New</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:disclaimer' %}">Disclaimer</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="table-responsive-md">
                    <table class="table table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">ToDo</th>
                                <th scope="col">Deadline</th>
                                <th scope="col">Progress</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if task_list %}
                                {% for task in task_list %}
                                    <tr>
                                        <th scope="row">{{ task.id }}</th>
                                        <td>{{ task.task_text }}</td>
                                        <td>{{ task.deadline }}</td>
                                        <td>
                                            <div class="progress">
                                                <div class="progress-bar progress-bar-striped" role="progressbar" style="width: {{ task.progress }}%;" aria-valuenow="{{ task.progress }}" aria-valuemin="0" aria-valuemax="100">{{ task.progress }}%</div>
                                            </div>
                                        </td>
                                        <td>
                                            <a class="btn btn-primary btn-sm" href="{% url 'todo:edit' task.id %}" role="button">edit</a>
                                            <a class="btn btn-danger btn-sm" href="{% url 'todo:delete' task.id %}" role="button">delete</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <th colspan="5">No ToDos in database.</th>
                                </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- How to use bootstrap -> https://www.youtube.com/watch?v=zcUUE0E_qAs -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'todo/js/jquery-3.4.0.slim.min.js' %}"></script>
    <script src="{% static 'todo/js/popper.min.js' %}"></script> <!-- https://github.com/FezVrasta/popper.js/blob/master/docs/_includes/tooltip-documentation.md -->
    <script src="{% static 'todo/js/bootstrap.js' %}"></script> <!-- https://getbootstrap.com/docs/4.3/getting-started/introduction/ -->
    <!-- <script src="{% static 'todo/js/own.js' %}"></script> https://www.w3schools.com/howto/howto_html_include.asp -->
    <!-- <script>includeHTML();</script> -->
</body>
</html>